spring:
  cloud:
    nacos:
      discovery:
        server-addr: "${NACOS_SERVER_ADDR}"
        username: "${NACOS_USERNAME}"
        password: "${NACOS_PASSWORD}"
    gateway:
      routes:
        - id: hoj-backend-user-service
          uri: lb://hoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: hoj-backend-question-service
          uri: lb://hoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: hoj-backend-judge-service
          uri: lb://hoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: hoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101


knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    strategy: discover
    discover:
      version: swagger2
